#pragma once

#define DEFAULT_EDITOR_FONT_FAMILY "Consolas" 
#define DEFAULT_EDITOR_FONT_SIZE 12
#define DEFAULT_EDITOR_TAB_SIZE 4
#define DEFAULT_EDITOR_INDENT_MODE "Spaces"
#define DEFAULT_EDITOR_COLOR_THEME "Default"
#define DEFAULT_EDITOR_STYLE_THEME "Dark"
